#!/bin/bash

read -p "enter your name" service

echo -e "$service"

if [ "$service" == "push" ] 
then
    git add .
    
    git commit -m 'd'

    git push 

    echo "pushed  Sir"

elif [ "$service" == "pull" ]
then
    git pull 
    
    echo "pulled Sir"
else
echo "is not working"
fi